package com.example.manjyot.app1;

import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.text.Layout;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import android.widget.Toast;

import org.w3c.dom.Text;

import java.util.ArrayList;

/**
 * Generated by Android Studio
 * Editted by manjyot on 25/01/2018.
 *
 */

public class FragmentAll extends Fragment {

    View myView;
    private ArrayList arrayTasks;
    private RecyclerView tRecyclerView;
    private TaskAdapter tAdapter;

    //Template task contents
    private String[] taskTitle = {"Revise chapter 1", "Complete assignment 2", "Attend lecture"};
    private String[] taskPriority = {"Low", "Medium", "High"};
    private String[] taskDate = {"01/05/2018", "02/05/2018", "03/05/2018"};


    @Override
    public void onCreate(Bundle savedInstanceState) {

        //Fill array list with task objects
        arrayTasks = new ArrayList();
        for (int i = 0; i < taskTitle.length; i++) {
            Task temp = new Task();
            temp.settTitle(taskTitle[i]);
            temp.settPriority(taskPriority[i]);
            temp.settDate(taskDate[i]);
            arrayTasks.add(temp);
        }

        super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
        myView = inflater.inflate(R.layout.frag_all, container, false);
        tRecyclerView = (RecyclerView) myView.findViewById(R.id.all_tasks_view);
        tRecyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));

        updateUI();
        return myView;
    }

    private void updateUI() {
        tAdapter = new TaskAdapter(arrayTasks);
        tRecyclerView.setAdapter(tAdapter);
    }

    private class TaskHolder extends RecyclerView.ViewHolder {
        private Task tempTask;
        public TextView tNameTextView;
        public TextView tDateTextView;

        public TaskHolder(View itemView) {
            super(itemView);

            //Identify the textView components in the layout
            tNameTextView = (TextView) itemView.findViewById(R.id.recycler_task_name);
            tDateTextView = (TextView) itemView.findViewById(R.id.recycler_task_date);

            //When one of the items in recycler is clicked
            itemView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    NavigationActivity.featureDialog.show();
                }
            });
        }

        public void bindTask(Task t) {
            tNameTextView.setText(t.gettTitle());
            tDateTextView.setText(t.gettDate());
        }
    }

    private class TaskAdapter extends RecyclerView.Adapter<TaskHolder> {
        private ArrayList<Task> tTasks;

        public TaskAdapter(ArrayList<Task> tasks) {
            tTasks = tasks;
        }

        /**
         * Creates view holder and inflates with layout file
         */
        @Override
        public TaskHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            LayoutInflater layoutInf = LayoutInflater.from(getActivity());
            View view = layoutInf.inflate(R.layout.recycler_view_task_item, parent, false);
            return new TaskHolder(view);
        }

        /**
         * Binds data to the view holder
         */
        @Override
        public void onBindViewHolder(TaskHolder holder, int pos) {
            Task t = tTasks.get(pos);
            holder.bindTask(t);
        }

        @Override
        public int getItemCount() {
            return tTasks.size();
        }


    }
}
